### ISSUE TITLE
About Inception v1(GoogleNet) pretrained weight

### ISSUE THREAD

**Issue by dandelin** [vadimkantorov/metriclearningbench#2]
Hello, thanks for sharing great codes.

Do you mind telling me where did you ported Inception v1’s pretrained weights from?

I’m just asking because according this discussion (https://discuss.pytorch.org/t/where-is-pretrained-googlenet-model/7845/4), torchvision team said they couldn’t reproduced original googlenet.

**Comment by vadimkantorov** [comment]
Unfortunately I don't remember anymore. I think it was BVLC's GoogLeNet which was ported
